Format Markdown
LatticeX-Foundation/Rosetta pull request #44
Opened 2021-01-24 19:00 UTC by 00make

2021-01-25 02:59 UTC, vingstar requested changes
Thank you for improving readability of our docs. 
Most of modification seems good, while some of them must be checked further, patiently.

2021-01-25 02:59 UTC, vingstar commented on README.md
> +![LOGO](doc/_static/figs/LOGO.png)
Currently, We use this link  on purpose so that more developers can view this LOGO.

2021-01-25 02:59 UTC, vingstar commented on doc/API_DOC.md
> +    For example, if dataset shape of P0 is N *d0, dataset shape of P1 is N* d1, and P2 has no data at all.
Obviously, the current one is better.

2021-01-25 20:33 UTC, 00make commented on README.md
> +![LOGO](doc/_static/figs/LOGO.png)
I'm currently helping Rosetta develop a tutorial website， http://119.3.214.209
During the development process, I  discovered that the WeChat pictures of qpic.cn directly copied to a third-party website couldn't be displayed, there was an anti-leech mechanism
提示：此图片来自微信公众平台 未经允许不得引用。
So I use absolute path to solve this problem, haven't found a perfect solution yet

PR is now changed to qpoc.cn，Both README & README_CN.

2021-01-25 20:33 UTC, 00make commented on doc/API_DOC.md
> +    For example, if dataset shape of P0 is N *d0, dataset shape of P1 is N* d1, and P2 has no data at all.
OK and updated

2021-01-28 02:03 UTC, vingstar commented
With the current version, these pages in http://119.3.214.209 seems good.
Please make sure these modification is backward compatible with the Github Markdown renderer.

generally, LGTM.

2021-01-28 06:25 UTC, merged